package Systems;

public class SystemVariables {
	public static final String STRING_LIST_PRODUC = "<!-- Page Heading -->\r\n"
			+ "                    <h1 class=\"h3 mb-2 text-gray-800\">Tables</h1>\r\n"
			+ "                    <p class=\"mb-4\" style=\"text-align: end;\"><button type=\"button\" class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#addProductModal\" data-bs-action=\"add\" fdprocessedid=\"v3x1qs\" id=\"js-btn-add-product\">Add Product</button></p>\r\n"
			+ "                    <!-- DataTales Example -->\r\n"
			+ "                    <div class=\"card shadow mb-4\">\r\n"
			+ "                        <div class=\"card-header py-3\">\r\n"
			+ "                            <h6 class=\"m-0 font-weight-bold text-primary\">DataTables Product</h6>\r\n"
			+ "                        </div>\r\n"
			+ "                        <div class=\"card-body\">\r\n"
			+ "                            <div class=\"table-responsive\">\r\n"
			+ "                                <table class=\"table table-bordered\" id=\"dataTable\" width=\"100%\" cellspacing=\"0\">\r\n"
			+ "                                    <thead>\r\n"
			+ "                                        <tr>\r\n"
			+ "                                            <th>Image</th>\r\n"
			+ "                                            <th>Name</th>\r\n"
			+ "                                            <th>Price</th>\r\n"
			+ "                                            <th>Date Created</th>\r\n"
			+ "                                            <th>Cancellation Date</th>\r\n"
			+ "                                            <th>Action</th>\r\n"
			+ "                                        </tr>\r\n"
			+ "                                    </thead>\r\n"
			+ "                                    <tfoot>\r\n"
			+ "                                        <tr>\r\n"
			+ "                                            <th>Image</th>\r\n"
			+ "                                            <th>Name</th>\r\n"
			+ "                                            <th>Price</th>\r\n"
			+ "                                            <th>Date Created</th>\r\n"
			+ "                                            <th>Cancellation Date</th>\r\n"
			+ "                                            <th>Action</th>\r\n"
			+ "                                        </tr>\r\n"
			+ "                                    </tfoot>\r\n"
			+ "                                    <tbody id=\"js-table-body\">\r\n"
			+ "                                        <tr>\r\n"
			+ "                                            <td>Tiger Nixon</td>\r\n"
			+ "                                            <td>System Architect</td>\r\n"
			+ "                                            <td>Edinburgh</td>\r\n"
			+ "                                            <td>61</td>\r\n"
			+ "                                            <td>2011/04/25</td>\r\n"
			+ "                                            <td>$320,800</td>\r\n"
			+ "                                        </tr>                                \r\n"
			+ "                                    </tbody>\r\n"
			+ "                                </table>\r\n"
			+ "                            </div>\r\n"
			+ "                        </div>\r\n"
			+ "                    </div>";
	public static final String STRING_LIST_COLOR = "<h1 class=\"h3 mb-2 text-gray-800\">Tables</h1>\r\n"
			+ "                    <p class=\"mb-4\" style=\"text-align: end;\"><button type=\"button\" class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#addColorModal\" data-bs-action=\"add\" fdprocessedid=\"v3x1qs\">Add Color</button></p>\r\n"
			+ "                    <!-- DataTales Example -->\r\n"
			+ "                    <div class=\"card shadow mb-4\">\r\n"
			+ "                        <div class=\"card-header py-3\">\r\n"
			+ "                            <h6 class=\"m-0 font-weight-bold text-primary\">DataTables Color</h6>\r\n"
			+ "                        </div>\r\n"
			+ "                        <div class=\"card-body\" id=\"js-table-responsive-inner-html\">\r\n"
			+ "                            <div class=\"table-responsive\">\r\n"
			+ "                                <table class=\"table table-bordered\" id=\"dataTable\" width=\"100%\" cellspacing=\"0\">\r\n"
			+ "                                    <thead>\r\n"
			+ "                                        <tr>\r\n"
			+ "                                            <th>STT</th>\r\n"
			+ "                                            <th>Name</th>\r\n"
			+ "                                            <th>Action</th>                                       \r\n"
			+ "                                        </tr>\r\n"
			+ "                                    </thead>\r\n"
			+ "                                    <tfoot>\r\n"
			+ "                                        <tr>\r\n"
			+ "                                            <th>STT</th>\r\n"
			+ "                                            <th>Name</th>\r\n"
			+ "                                            <th>Action</th>\r\n"
			+ "                                        </tr>\r\n"
			+ "                                    </tfoot>\r\n"
			+ "                                    <tbody id=\"js-table-body\">\r\n"
			+ "                                        <tr>\r\n"
			+ "                                            <td>Tiger Nixon</td>\r\n"
			+ "                                            <td>System Architect</td>\r\n"
			+ "                                            <td>Edinburgh</td>\r\n"
			+ "                                        </tr>                                \r\n"
			+ "                                    </tbody>\r\n"
			+ "                                </table>\r\n"
			+ "                            </div>\r\n"
			+ "                        </div>\r\n"
			+ "                    </div>";
	public static final String STRING_LIST_ORDER = "<!-- Page Heading -->\r\n"
			+ "                    <h1 class=\"h3 mb-2 text-gray-800\">Tables Order</h1>              \r\n"
			+ "                    <!-- DataTales Example -->\r\n"
			+ "                    <div class=\"card shadow mb-4\">\r\n"
			+ "                        <div class=\"card-header py-3\">\r\n"
			+ "                            <h6 class=\"m-0 font-weight-bold text-primary\">DataTables Order</h6>\r\n"
			+ "                        </div>\r\n"
			+ "                        <div class=\"card-body\" id=\"js-table-responsive-inner-html\">\r\n"
			+ "                            <div class=\"table-responsive\">\r\n"
			+ "                                <table class=\"table table-bordered\" id=\"dataTable\" width=\"100%\" cellspacing=\"0\">\r\n"
			+ "                                    <thead>\r\n"
			+ "                                        <tr>\r\n"
			+ "                                            <th>Order Code</th>\r\n"
			+ "                                            <th>Name</th>\r\n"
			+ "                                            <th>Phone</th>\r\n"
			+ "                                            <th>Email</th>\r\n"
			+ "                                            <th>Address</th>\r\n"
			+ "                                            <th>Order status</th>\r\n"
			+ "					    <th>Date created</th>\r\n"
			+ "					    <th>Money</th>\r\n"
			+ "                                        </tr>\r\n"
			+ "                                    </thead>\r\n"
			+ "                                    <tfoot>\r\n"
			+ "                                        <tr>\r\n"
			+ "                                            <th>Order Code</th>\r\n"
			+ "                                            <th>Name</th>\r\n"
			+ "                                            <th>Phone</th>\r\n"
			+ "                                            <th>Email</th>\r\n"
			+ "                                            <th>Address</th>\r\n"
			+ "                                            <th>Order status</th>\r\n"
			+ "					    <th>Date created</th>\r\n"
			+ "					    <th>Money</th>\r\n"
			+ "                                        </tr>\r\n"
			+ "                                    </tfoot>\r\n"
			+ "                                    <tbody id=\"js-table-body\">\r\n"
			+ "                                        <tr>\r\n"
			+ "                                            <td>Tiger Nixon</td>\r\n"
			+ "                                            <td>System Architect</td>\r\n"
			+ "                                            <td>Edinburgh</td>\r\n"
			+ "                                            <td>61</td>\r\n"
			+ "                                            <td>2011/04/25</td>\r\n"
			+ "                                            <td>$320,800</td>\r\n"
			+ "					    <td>$320,800</td>\r\n"
			+ "                    			    <td>$320,800</td>\r\n"
			+ "                                        </tr>                                \r\n"
			+ "                                    </tbody>\r\n"
			+ "                                </table>\r\n"
			+ "                            </div>\r\n"
			+ "                        </div>\r\n"
			+ "                    </div>";
}
